apiVersion: v1
kind: Service
metadata:
  name: rmgaas-api
  namespace: rmgaas
  labels:
    app.kubernetes.io/name: rmgaas
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rmgaas
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
