-- Extend AuditAction enum for request and override outcome traceability
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REQUEST_RETURNED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REQUEST_CANCELLED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OVERRIDE_APPROVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OVERRIDE_REJECTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OVERRIDE_EXPIRED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OVERRIDE_CANCELLED';
