import {
  Priority,
  RequestCategory,
  RequestVisibility,
  RollbackPermission,
  SlaCalculationType,
} from '@prisma/client';

import {
  parseRequestBlueprintDefinition,
  type RequestBlueprintV1,
} from './request-blueprint.schemas';

export interface RequestPackSeedDefinition {
  code: string;
  name: string;
  description: string;
  domain: RequestBlueprintV1['identity']['domain'];
  maturityLevel: RequestBlueprintV1['identity']['maturityLevel'];
  iconName: string;
  sortOrder: number;
  recommendedOrgProfiles: string[];
  activationDependencies: {
    requiredFoundations: string[];
    placeholderRoles: Array<{
      code: string;
      required: boolean;
    }>;
  };
}

export interface RequestTypeSeedDefinition {
  code: string;
  name: string;
  description: string;
  category: RequestCategory;
  defaultPriority: Priority;
  responseSlaHours: number;
  resolutionSlaHours: number;
  slaCalculationType: SlaCalculationType;
  requiresApproval: boolean;
  allowRollback: boolean;
  rollbackWindowDays: number;
  rollbackPermission: RollbackPermission;
  visibilityScope: RequestVisibility;
  onApprovalHandler: string | null;
  formSchema: unknown;
  requiredFields: string[];
}

const urgencyCondition = {
  operator: 'AND' as const,
  conditions: [{ left: 'priority', op: 'EQUALS' as const, right: 'CRITICAL' }],
};

const titleField = {
  key: 'title' as const,
  visible: true,
  editable: true,
  requiredForDraft: true,
  requiredForSubmit: true,
};

const descriptionField = {
  key: 'description' as const,
  visible: true,
  editable: true,
  requiredForDraft: false,
  requiredForSubmit: false,
};

const priorityField = {
  key: 'priority' as const,
  visible: true,
  editable: true,
  requiredForDraft: false,
  requiredForSubmit: false,
  defaultValue: 'MEDIUM',
};

const urgencyField = {
  key: 'urgencyJustification' as const,
  visible: true,
  editable: true,
  requiredForDraft: false,
  requiredForSubmit: false,
  requirementCondition: urgencyCondition,
};

const neededByField = {
  key: 'neededBy' as const,
  visible: true,
  editable: true,
  requiredForDraft: false,
  requiredForSubmit: false,
};

const attachmentsField = {
  key: 'attachments' as const,
  visible: true,
  editable: true,
  requiredForDraft: false,
  requiredForSubmit: false,
};

export const professionalServicesCorePack: RequestPackSeedDefinition = {
  code: 'PRO_SERVICES_CORE',
  name: 'Professional Services Core',
  description:
    'Default operational pack for customer onboarding, commercial setup, project setup, and staffing flows.',
  domain: 'PROFESSIONAL_SERVICES',
  maturityLevel: 'STANDARD',
  iconName: 'briefcase-business',
  sortOrder: 1,
  recommendedOrgProfiles: ['PROFESSIONAL_SERVICES', 'IT_SERVICES', 'CONSULTING'],
  activationDependencies: {
    requiredFoundations: [
      'tenant_identity_configured',
      'org_structure_available',
      'users_available_for_mapping',
      'business_roles_configured',
    ],
    placeholderRoles: [
      { code: 'ACCOUNT_OWNER', required: true },
      { code: 'DELIVERY_OWNER', required: true },
      { code: 'PROJECT_MANAGER', required: true },
      { code: 'PRACTICE_LEAD', required: true },
      { code: 'FINANCE_APPROVER', required: true },
      { code: 'SALES_APPROVER', required: false },
      { code: 'PMO_APPROVER', required: false },
    ],
  },
};

export const professionalServicesCoreRequestTypes: RequestTypeSeedDefinition[] = [
  {
    code: 'CUSTOMER_ONBOARDING',
    name: 'Customer Onboarding',
    description: 'Create or formalize customer context for downstream commercial and delivery setup.',
    category: RequestCategory.OTHER,
    defaultPriority: Priority.MEDIUM,
    responseSlaHours: 24,
    resolutionSlaHours: 72,
    slaCalculationType: SlaCalculationType.BUSINESS_HOURS,
    requiresApproval: true,
    allowRollback: true,
    rollbackWindowDays: 30,
    rollbackPermission: RollbackPermission.ADMIN_ONLY,
    visibilityScope: RequestVisibility.TENANT,
    onApprovalHandler: null,
    formSchema: {
      type: 'object',
      description: 'Blueprint-driven intake. See RequestBlueprint for runtime form configuration.',
      properties: {
        client: { type: 'string', title: 'Client' },
        customerLegalName: { type: 'string', title: 'Customer Legal Name' },
        primaryContactEmail: { type: 'string', format: 'email', title: 'Primary Contact Email' },
        engagementOwner: { type: 'string', title: 'Engagement Owner' },
      },
    },
    requiredFields: ['customerLegalName', 'primaryContactEmail', 'engagementOwner'],
  },
  {
    code: 'MSA_CREATION',
    name: 'MSA Creation',
    description: 'Initiate master agreement setup for an onboarded customer.',
    category: RequestCategory.CONTRACT,
    defaultPriority: Priority.MEDIUM,
    responseSlaHours: 24,
    resolutionSlaHours: 96,
    slaCalculationType: SlaCalculationType.BUSINESS_HOURS,
    requiresApproval: true,
    allowRollback: true,
    rollbackWindowDays: 30,
    rollbackPermission: RollbackPermission.ADMIN_ONLY,
    visibilityScope: RequestVisibility.TENANT,
    onApprovalHandler: null,
    formSchema: {
      type: 'object',
      description: 'Blueprint-driven intake. See RequestBlueprint for runtime form configuration.',
      properties: {
        client: { type: 'string', title: 'Client' },
        priorRequest: { type: 'string', title: 'Customer Onboarding Request' },
        contractingEntity: { type: 'string', title: 'Contracting Entity' },
        commercialOwner: { type: 'string', title: 'Commercial Owner' },
      },
    },
    requiredFields: ['client', 'priorRequest', 'contractingEntity', 'commercialOwner'],
  },
  {
    code: 'SOW_CREATION',
    name: 'SOW Creation',
    description: 'Define the scoped commercial delivery statement tied to an MSA.',
    category: RequestCategory.CONTRACT,
    defaultPriority: Priority.MEDIUM,
    responseSlaHours: 24,
    resolutionSlaHours: 96,
    slaCalculationType: SlaCalculationType.BUSINESS_HOURS,
    requiresApproval: true,
    allowRollback: true,
    rollbackWindowDays: 30,
    rollbackPermission: RollbackPermission.ADMIN_ONLY,
    visibilityScope: RequestVisibility.TENANT,
    onApprovalHandler: null,
    formSchema: {
      type: 'object',
      description: 'Blueprint-driven intake. See RequestBlueprint for runtime form configuration.',
      properties: {
        client: { type: 'string', title: 'Client' },
        contract: { type: 'string', title: 'MSA Contract' },
        priorRequest: { type: 'string', title: 'MSA Creation Request' },
        serviceLine: { type: 'string', title: 'Service Line' },
        targetStartDate: { type: 'string', format: 'date', title: 'Target Start Date' },
      },
    },
    requiredFields: ['client', 'contract', 'priorRequest', 'serviceLine', 'targetStartDate'],
  },
  {
    code: 'PROJECT_SETUP',
    name: 'Project Setup',
    description: 'Create the project delivery context after commercial approval is in place.',
    category: RequestCategory.PROJECT,
    defaultPriority: Priority.MEDIUM,
    responseSlaHours: 24,
    resolutionSlaHours: 120,
    slaCalculationType: SlaCalculationType.BUSINESS_HOURS,
    requiresApproval: true,
    allowRollback: true,
    rollbackWindowDays: 30,
    rollbackPermission: RollbackPermission.ADMIN_ONLY,
    visibilityScope: RequestVisibility.TENANT,
    onApprovalHandler: null,
    formSchema: {
      type: 'object',
      description: 'Blueprint-driven intake. See RequestBlueprint for runtime form configuration.',
      properties: {
        client: { type: 'string', title: 'Client' },
        contract: { type: 'string', title: 'Contract' },
        priorRequest: { type: 'string', title: 'SOW Creation Request' },
        projectName: { type: 'string', title: 'Project Name' },
        deliveryOwner: { type: 'string', title: 'Delivery Owner' },
        projectManager: { type: 'string', title: 'Project Manager' },
      },
    },
    requiredFields: ['client', 'contract', 'priorRequest', 'projectName', 'deliveryOwner', 'projectManager'],
  },
  {
    code: 'RESOURCE_ALLOCATION_BATCH',
    name: 'Resource Allocation',
    description: 'Request one or more resource allocations against a prepared project.',
    category: RequestCategory.RESOURCE,
    defaultPriority: Priority.MEDIUM,
    responseSlaHours: 24,
    resolutionSlaHours: 72,
    slaCalculationType: SlaCalculationType.BUSINESS_HOURS,
    requiresApproval: true,
    allowRollback: true,
    rollbackWindowDays: 30,
    rollbackPermission: RollbackPermission.ADMIN_ONLY,
    visibilityScope: RequestVisibility.TENANT,
    onApprovalHandler: 'AllocationRequestHandler.execute',
    formSchema: {
      type: 'object',
      description: 'Blueprint-driven intake. See RequestBlueprint for runtime form configuration.',
      properties: {
        project: { type: 'string', title: 'Project' },
        priorRequest: { type: 'string', title: 'Project Setup Request' },
        requestedStartDate: { type: 'string', format: 'date', title: 'Requested Start Date' },
        requestedSkill: { type: 'string', title: 'Required Skill / Role' },
        headcount: { type: 'integer', title: 'Headcount', minimum: 1 },
      },
    },
    requiredFields: ['project', 'priorRequest', 'requestedStartDate', 'requestedSkill', 'headcount'],
  },
  {
    code: 'PMO_OPERATIONAL_EXCEPTION',
    name: 'PMO Operational Exception',
    description: 'Escalate PMO-controlled operational exceptions such as document mismatches, commercial blockers, and rollback requests.',
    category: RequestCategory.OTHER,
    defaultPriority: Priority.HIGH,
    responseSlaHours: 8,
    resolutionSlaHours: 24,
    slaCalculationType: SlaCalculationType.BUSINESS_HOURS,
    requiresApproval: true,
    allowRollback: false,
    rollbackWindowDays: 0,
    rollbackPermission: RollbackPermission.ADMIN_ONLY,
    visibilityScope: RequestVisibility.TENANT,
    onApprovalHandler: null,
    formSchema: {
      type: 'object',
      description: 'Blueprint-driven intake for PMO operational exceptions.',
      properties: {
        exceptionType: { type: 'string', title: 'Exception Type' },
        impactSummary: { type: 'string', title: 'Impact Summary' },
        requestedDisposition: { type: 'string', title: 'Requested Disposition' },
        accountableOwner: { type: 'string', title: 'Accountable Owner' },
      },
    },
    requiredFields: ['exceptionType', 'impactSummary', 'requestedDisposition', 'accountableOwner'],
  },
];

function blueprint(input: RequestBlueprintV1): RequestBlueprintV1 {
  return parseRequestBlueprintDefinition(input);
}

export const professionalServicesCoreBlueprints: RequestBlueprintV1[] = [
  blueprint({
    schemaVersion: '1.0',
    identity: {
      code: 'CUSTOMER_ONBOARDING',
      name: 'Customer Onboarding',
      description: 'Create or formalize customer context required for downstream commercial and delivery setup.',
      domain: 'PROFESSIONAL_SERVICES',
      category: 'Customer Setup',
      icon: 'building-2',
      version: 1,
      isSystemBlueprint: true,
      packCode: professionalServicesCorePack.code,
      maturityLevel: 'STANDARD',
    },
    runtime: {
      renderMode: 'DRAWER',
      complexityLevel: 'STANDARD',
      allowDraft: true,
      allowSubmit: true,
      allowEditAfterReturn: true,
      allowAttachments: true,
      maxAttachments: 5,
      maxAttachmentSizeMb: 10,
    },
    commonFields: [titleField, descriptionField, priorityField, urgencyField, neededByField, attachmentsField],
    entityBindings: [
      {
        key: 'client',
        entityType: 'client',
        label: 'Client',
        visible: true,
        editable: true,
        selectionMode: 'SINGLE',
        requiredForDraft: false,
        requiredForSubmit: false,
        autoResolve: false,
        allowManualSelection: true,
        helpText: 'Select an existing client or leave blank to create new customer context in this request.',
      },
    ],
    customFields: [
      { fieldKey: 'customerLegalName', label: 'Customer Legal Name', type: 'TEXT', displayOrder: 1, requiredForDraft: false, requiredForSubmit: true },
      { fieldKey: 'customerDisplayName', label: 'Customer Display Name', type: 'TEXT', displayOrder: 2, requiredForDraft: false, requiredForSubmit: false },
      {
        fieldKey: 'customerType',
        label: 'Customer Type',
        type: 'SELECT',
        displayOrder: 3,
        requiredForDraft: false,
        requiredForSubmit: false,
        options: [
          { label: 'New', value: 'NEW' },
          { label: 'Existing', value: 'EXISTING' },
        ],
      },
      { fieldKey: 'billingCountry', label: 'Billing Country', type: 'TEXT', displayOrder: 4, requiredForDraft: false, requiredForSubmit: false },
      { fieldKey: 'primaryContactName', label: 'Primary Contact Name', type: 'TEXT', displayOrder: 5, requiredForDraft: false, requiredForSubmit: true },
      {
        fieldKey: 'primaryContactEmail',
        label: 'Primary Contact Email',
        type: 'TEXT',
        displayOrder: 6,
        requiredForDraft: false,
        requiredForSubmit: true,
        validation: [{ type: 'REGEX', value: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$', message: 'Enter a valid email address.' }],
      },
      { fieldKey: 'engagementOwner', label: 'Engagement Owner', type: 'USER_PICKER', displayOrder: 7, requiredForDraft: false, requiredForSubmit: true },
      { fieldKey: 'expectedStartWindow', label: 'Expected Start Window', type: 'DATE', displayOrder: 8, requiredForDraft: false, requiredForSubmit: false },
      { fieldKey: 'notes', label: 'Notes', type: 'TEXTAREA', displayOrder: 9, requiredForDraft: false, requiredForSubmit: false },
    ],
    dependencyRules: [],
    workflowPolicy: {
      requiresApproval: true,
      workflowTemplateCode: 'CUSTOMER_ONBOARDING_DEFAULT',
      slaProfileCode: 'STANDARD_OPERATIONS',
      defaultPriority: 'MEDIUM',
      autoApproveWhenNoChainResolved: false,
    },
    overridePolicy: {
      editableSections: ['identity-labels', 'commonFields', 'workflowPolicy'],
      mode: 'STANDARD_EDITABLE',
    },
  }),
  blueprint({
    schemaVersion: '1.0',
    identity: {
      code: 'MSA_CREATION',
      name: 'MSA Creation',
      description: 'Create the commercial agreement context that downstream SOW and project setup depend on.',
      domain: 'PROFESSIONAL_SERVICES',
      category: 'Commercial Setup',
      icon: 'file-signature',
      version: 1,
      isSystemBlueprint: true,
      packCode: professionalServicesCorePack.code,
      maturityLevel: 'STANDARD',
    },
    runtime: {
      renderMode: 'DRAWER',
      complexityLevel: 'STANDARD',
      allowDraft: true,
      allowSubmit: true,
      allowEditAfterReturn: true,
      allowAttachments: true,
      maxAttachments: 5,
      maxAttachmentSizeMb: 10,
    },
    commonFields: [titleField, descriptionField, priorityField, urgencyField, neededByField, attachmentsField],
    entityBindings: [
      {
        key: 'client',
        entityType: 'client',
        label: 'Client',
        visible: true,
        editable: true,
        selectionMode: 'SINGLE',
        requiredForDraft: false,
        requiredForSubmit: true,
        autoResolve: false,
        allowManualSelection: true,
      },
      {
        key: 'customerOnboardingRequest',
        entityType: 'priorRequest',
        label: 'Customer Onboarding Request',
        visible: true,
        editable: true,
        selectionMode: 'SINGLE',
        requiredForDraft: false,
        requiredForSubmit: true,
        autoResolve: true,
        allowManualSelection: true,
        helpText: 'Link a completed customer onboarding request before submission.',
        resolutionPolicy: {
          strategy: 'PROMPT_ON_AMBIGUITY',
          emptyStateMessage: 'Create and complete a customer onboarding request first.',
          multipleMatchMessage: 'Multiple completed onboarding requests were found. Choose the correct one.',
        },
      },
    ],
    customFields: [
      {
        fieldKey: 'msaType',
        label: 'MSA Type',
        type: 'SELECT',
        displayOrder: 1,
        requiredForDraft: false,
        requiredForSubmit: false,
        options: [
          { label: 'Standard', value: 'STANDARD' },
          { label: 'Amendment', value: 'AMENDMENT' },
          { label: 'Renewal', value: 'RENEWAL' },
        ],
      },
      { fieldKey: 'contractingEntity', label: 'Contracting Entity', type: 'TEXT', displayOrder: 2, requiredForDraft: false, requiredForSubmit: true },
      { fieldKey: 'commercialOwner', label: 'Commercial Owner', type: 'USER_PICKER', displayOrder: 3, requiredForDraft: false, requiredForSubmit: true },
      { fieldKey: 'effectiveDateTarget', label: 'Effective Date Target', type: 'DATE', displayOrder: 4, requiredForDraft: false, requiredForSubmit: false },
      {
        fieldKey: 'renewalModel',
        label: 'Renewal Model',
        type: 'SELECT',
        displayOrder: 5,
        requiredForDraft: false,
        requiredForSubmit: false,
        options: [
          { label: 'Evergreen', value: 'EVERGREEN' },
          { label: 'Fixed Term', value: 'FIXED_TERM' },
          { label: 'Auto Renew', value: 'AUTO_RENEW' },
        ],
      },
      { fieldKey: 'governingRegion', label: 'Governing Region', type: 'TEXT', displayOrder: 6, requiredForDraft: false, requiredForSubmit: false },
      { fieldKey: 'specialTermsFlag', label: 'Special Terms Flag', type: 'CHECKBOX', displayOrder: 7, requiredForDraft: false, requiredForSubmit: false },
    ],
    dependencyRules: [
      {
        ruleKey: 'requires-customer-onboarding',
        dependencyType: 'PRIOR_REQUEST',
        blockingStage: 'SUBMIT',
        message: 'A completed Customer Onboarding request must be linked before submission.',
        requiredRequestTypeCode: 'CUSTOMER_ONBOARDING',
        requiredStatus: 'COMPLETED',
        requiredEntityBindingKey: 'customerOnboardingRequest',
        resolutionMode: 'AUTO_OR_PICK',
        autoResolveIfSingle: true,
        promptIfMultiple: true,
      },
    ],
    workflowPolicy: {
      requiresApproval: true,
      workflowTemplateCode: 'MSA_CREATION_DEFAULT',
      slaProfileCode: 'STANDARD_OPERATIONS',
      defaultPriority: 'MEDIUM',
      autoApproveWhenNoChainResolved: false,
    },
    overridePolicy: {
      editableSections: ['identity-labels', 'commonFields', 'entityBindings', 'workflowPolicy'],
      mode: 'STANDARD_EDITABLE',
    },
  }),
  blueprint({
    schemaVersion: '1.0',
    identity: {
      code: 'SOW_CREATION',
      name: 'SOW Creation',
      description: 'Provide the statement of work context required before project setup.',
      domain: 'PROFESSIONAL_SERVICES',
      category: 'Commercial Setup',
      icon: 'file-text',
      version: 1,
      isSystemBlueprint: true,
      packCode: professionalServicesCorePack.code,
      maturityLevel: 'STANDARD',
    },
    runtime: {
      renderMode: 'PAGE',
      complexityLevel: 'ADVANCED',
      allowDraft: true,
      allowSubmit: true,
      allowEditAfterReturn: true,
      allowAttachments: true,
      maxAttachments: 5,
      maxAttachmentSizeMb: 10,
    },
    commonFields: [titleField, descriptionField, priorityField, urgencyField, neededByField, attachmentsField],
    entityBindings: [
      {
        key: 'client',
        entityType: 'client',
        label: 'Client',
        visible: true,
        editable: true,
        selectionMode: 'SINGLE',
        requiredForDraft: false,
        requiredForSubmit: true,
        autoResolve: false,
        allowManualSelection: true,
      },
      {
        key: 'contract',
        entityType: 'contract',
        label: 'MSA Contract',
        visible: true,
        editable: true,
        selectionMode: 'SINGLE',
        requiredForDraft: false,
        requiredForSubmit: true,
        autoResolve: false,
        allowManualSelection: true,
      },
      {
        key: 'msaCreationRequest',
        entityType: 'priorRequest',
        label: 'MSA Creation Request',
        visible: true,
        editable: true,
        selectionMode: 'SINGLE',
        requiredForDraft: false,
        requiredForSubmit: true,
        autoResolve: true,
        allowManualSelection: true,
        resolutionPolicy: {
          strategy: 'PROMPT_ON_AMBIGUITY',
          emptyStateMessage: 'Complete an MSA Creation request before submitting this SOW.',
          multipleMatchMessage: 'Multiple completed MSA requests were found. Select the correct request.',
        },
      },
    ],
    customFields: [
      { fieldKey: 'sowReference', label: 'SOW Reference', type: 'TEXT', displayOrder: 1, requiredForDraft: false, requiredForSubmit: false },
      { fieldKey: 'serviceLine', label: 'Service Line', type: 'TEXT', displayOrder: 2, requiredForDraft: false, requiredForSubmit: true },
      {
        fieldKey: 'deliveryModel',
        label: 'Delivery Model',
        type: 'SELECT',
        displayOrder: 3,
        requiredForDraft: false,
        requiredForSubmit: false,
        options: [
          { label: 'Managed Services', value: 'MANAGED_SERVICES' },
          { label: 'Project', value: 'PROJECT' },
          { label: 'Augmentation', value: 'AUGMENTATION' },
        ],
      },
      {
        fieldKey: 'billingModel',
        label: 'Billing Model',
        type: 'SELECT',
        displayOrder: 4,
        requiredForDraft: false,
        requiredForSubmit: false,
        options: [
          { label: 'Time and Materials', value: 'T_AND_M' },
          { label: 'Fixed Bid', value: 'FIXED_BID' },
          { label: 'Milestone', value: 'MILESTONE' },
        ],
      },
      { fieldKey: 'targetStartDate', label: 'Target Start Date', type: 'DATE', displayOrder: 5, requiredForDraft: false, requiredForSubmit: true },
      { fieldKey: 'targetEndDate', label: 'Target End Date', type: 'DATE', displayOrder: 6, requiredForDraft: false, requiredForSubmit: false },
      { fieldKey: 'commercialSummary', label: 'Commercial Summary', type: 'TEXTAREA', displayOrder: 7, requiredForDraft: false, requiredForSubmit: false },
      { fieldKey: 'scopeSummary', label: 'Scope Summary', type: 'TEXTAREA', displayOrder: 8, requiredForDraft: false, requiredForSubmit: false },
      { fieldKey: 'assumptions', label: 'Assumptions', type: 'TEXTAREA', displayOrder: 9, requiredForDraft: false, requiredForSubmit: false },
      { fieldKey: 'dependencyNotes', label: 'Dependency Notes', type: 'TEXTAREA', displayOrder: 10, requiredForDraft: false, requiredForSubmit: false },
    ],
    dependencyRules: [
      {
        ruleKey: 'requires-msa-creation',
        dependencyType: 'PRIOR_REQUEST',
        blockingStage: 'SUBMIT',
        message: 'A completed MSA Creation request must be linked before submission.',
        requiredRequestTypeCode: 'MSA_CREATION',
        requiredStatus: 'COMPLETED',
        requiredEntityBindingKey: 'msaCreationRequest',
        resolutionMode: 'AUTO_OR_PICK',
        autoResolveIfSingle: true,
        promptIfMultiple: true,
      },
    ],
    workflowPolicy: {
      requiresApproval: true,
      workflowTemplateCode: 'SOW_CREATION_DEFAULT',
      slaProfileCode: 'STANDARD_OPERATIONS',
      defaultPriority: 'MEDIUM',
      autoApproveWhenNoChainResolved: false,
    },
    overridePolicy: {
      editableSections: ['identity-labels', 'commonFields', 'entityBindings', 'customFields', 'workflowPolicy'],
      mode: 'STANDARD_EDITABLE',
    },
  }),
  blueprint({
    schemaVersion: '1.0',
    identity: {
      code: 'PROJECT_SETUP',
      name: 'Project Setup',
      description: 'Establish the project shell, ownership, and delivery structure required before staffing.',
      domain: 'PROFESSIONAL_SERVICES',
      category: 'Delivery Setup',
      icon: 'folder-kanban',
      version: 1,
      isSystemBlueprint: true,
      packCode: professionalServicesCorePack.code,
      maturityLevel: 'STANDARD',
    },
    runtime: {
      renderMode: 'PAGE',
      complexityLevel: 'ADVANCED',
      allowDraft: true,
      allowSubmit: true,
      allowEditAfterReturn: true,
      allowAttachments: true,
      maxAttachments: 5,
      maxAttachmentSizeMb: 10,
    },
    commonFields: [titleField, descriptionField, priorityField, neededByField, attachmentsField],
    entityBindings: [
      {
        key: 'client',
        entityType: 'client',
        label: 'Client',
        visible: true,
        editable: true,
        selectionMode: 'SINGLE',
        requiredForDraft: false,
        requiredForSubmit: true,
        autoResolve: false,
        allowManualSelection: true,
      },
      {
        key: 'contract',
        entityType: 'contract',
        label: 'Contract',
        visible: true,
        editable: true,
        selectionMode: 'SINGLE',
        requiredForDraft: false,
        requiredForSubmit: true,
        autoResolve: false,
        allowManualSelection: true,
      },
      {
        key: 'sowCreationRequest',
        entityType: 'priorRequest',
        label: 'SOW Creation Request',
        visible: true,
        editable: true,
        selectionMode: 'SINGLE',
        requiredForDraft: false,
        requiredForSubmit: true,
        autoResolve: true,
        allowManualSelection: true,
        resolutionPolicy: {
          strategy: 'PROMPT_ON_AMBIGUITY',
          emptyStateMessage: 'Complete an SOW Creation request before submitting this project setup.',
          multipleMatchMessage: 'Multiple completed SOW requests were found. Select the correct request.',
        },
      },
    ],
    customFields: [
      { fieldKey: 'proposedProjectCode', label: 'Proposed Project Code', type: 'TEXT', displayOrder: 1, requiredForDraft: false, requiredForSubmit: false },
      { fieldKey: 'projectName', label: 'Project Name', type: 'TEXT', displayOrder: 2, requiredForDraft: false, requiredForSubmit: true },
      { fieldKey: 'deliveryOwner', label: 'Delivery Owner', type: 'USER_PICKER', displayOrder: 3, requiredForDraft: false, requiredForSubmit: true },
      { fieldKey: 'projectManager', label: 'Project Manager', type: 'USER_PICKER', displayOrder: 4, requiredForDraft: false, requiredForSubmit: true },
      { fieldKey: 'practiceUnit', label: 'Practice / Delivery Unit', type: 'TEXT', displayOrder: 5, requiredForDraft: false, requiredForSubmit: false },
      { fieldKey: 'costCenter', label: 'Cost Center', type: 'TEXT', displayOrder: 6, requiredForDraft: false, requiredForSubmit: false },
      {
        fieldKey: 'billabilityModel',
        label: 'Billability Model',
        type: 'SELECT',
        displayOrder: 7,
        requiredForDraft: false,
        requiredForSubmit: false,
        options: [
          { label: 'Billable', value: 'BILLABLE' },
          { label: 'Non-Billable', value: 'NON_BILLABLE' },
          { label: 'Mixed', value: 'MIXED' },
        ],
      },
      { fieldKey: 'marginTrackingRequired', label: 'Margin Tracking Required', type: 'CHECKBOX', displayOrder: 8, requiredForDraft: false, requiredForSubmit: false },
      { fieldKey: 'targetStartDate', label: 'Target Start Date', type: 'DATE', displayOrder: 9, requiredForDraft: false, requiredForSubmit: true },
      {
        fieldKey: 'reportingCadence',
        label: 'Reporting Cadence',
        type: 'SELECT',
        displayOrder: 10,
        requiredForDraft: false,
        requiredForSubmit: false,
        options: [
          { label: 'Weekly', value: 'WEEKLY' },
          { label: 'Biweekly', value: 'BIWEEKLY' },
          { label: 'Monthly', value: 'MONTHLY' },
        ],
      },
    ],
    dependencyRules: [
      {
        ruleKey: 'requires-sow-creation',
        dependencyType: 'PRIOR_REQUEST',
        blockingStage: 'SUBMIT',
        message: 'A completed SOW Creation request must be linked before submission.',
        requiredRequestTypeCode: 'SOW_CREATION',
        requiredStatus: 'COMPLETED',
        requiredEntityBindingKey: 'sowCreationRequest',
        resolutionMode: 'AUTO_OR_PICK',
        autoResolveIfSingle: true,
        promptIfMultiple: true,
      },
    ],
    workflowPolicy: {
      requiresApproval: true,
      workflowTemplateCode: 'PROJECT_SETUP_DEFAULT',
      slaProfileCode: 'STANDARD_OPERATIONS',
      defaultPriority: 'MEDIUM',
      autoApproveWhenNoChainResolved: false,
    },
    overridePolicy: {
      editableSections: ['identity-labels', 'commonFields', 'entityBindings', 'customFields', 'workflowPolicy'],
      mode: 'STANDARD_EDITABLE',
    },
  }),
  blueprint({
    schemaVersion: '1.0',
    identity: {
      code: 'RESOURCE_ALLOCATION_BATCH',
      name: 'Resource Allocation',
      description: 'Request one or more resource allocations against a prepared project.',
      domain: 'PROFESSIONAL_SERVICES',
      category: 'Staffing',
      icon: 'users-round',
      version: 1,
      isSystemBlueprint: true,
      packCode: professionalServicesCorePack.code,
      maturityLevel: 'STANDARD',
    },
    runtime: {
      renderMode: 'PAGE',
      complexityLevel: 'ADVANCED',
      allowDraft: true,
      allowSubmit: true,
      allowEditAfterReturn: true,
      allowAttachments: true,
      maxAttachments: 5,
      maxAttachmentSizeMb: 10,
    },
    commonFields: [titleField, descriptionField, priorityField, urgencyField, neededByField, attachmentsField],
    entityBindings: [
      {
        key: 'project',
        entityType: 'project',
        label: 'Project',
        visible: true,
        editable: true,
        selectionMode: 'SINGLE',
        requiredForDraft: false,
        requiredForSubmit: true,
        autoResolve: false,
        allowManualSelection: true,
      },
      {
        key: 'client',
        entityType: 'client',
        label: 'Client',
        visible: true,
        editable: false,
        selectionMode: 'SINGLE',
        requiredForDraft: false,
        requiredForSubmit: false,
        autoResolve: true,
        allowManualSelection: false,
        derivedFrom: 'project',
      },
      {
        key: 'contract',
        entityType: 'contract',
        label: 'Contract',
        visible: true,
        editable: false,
        selectionMode: 'SINGLE',
        requiredForDraft: false,
        requiredForSubmit: false,
        autoResolve: true,
        allowManualSelection: false,
        derivedFrom: 'projectSetupRequest',
      },
      {
        key: 'projectSetupRequest',
        entityType: 'priorRequest',
        label: 'Project Setup Request',
        visible: true,
        editable: true,
        selectionMode: 'SINGLE',
        requiredForDraft: false,
        requiredForSubmit: true,
        autoResolve: true,
        allowManualSelection: true,
        resolutionPolicy: {
          strategy: 'PROMPT_ON_AMBIGUITY',
          emptyStateMessage: 'Complete a Project Setup request before submitting this staffing request.',
          multipleMatchMessage: 'Multiple completed project setup requests were found. Select the correct one.',
        },
      },
    ],
    customFields: [
      {
        fieldKey: 'allocationMode',
        label: 'Allocation Mode',
        type: 'RADIO',
        displayOrder: 1,
        requiredForDraft: false,
        requiredForSubmit: false,
        options: [
          { label: 'Single Request', value: 'SINGLE' },
          { label: 'Batch Request', value: 'BATCH' },
        ],
      },
      { fieldKey: 'requestedStartDate', label: 'Requested Start Date', type: 'DATE', displayOrder: 2, requiredForDraft: false, requiredForSubmit: true },
      { fieldKey: 'requestedEndDate', label: 'Requested End Date', type: 'DATE', displayOrder: 3, requiredForDraft: false, requiredForSubmit: false },
      { fieldKey: 'requestedSkill', label: 'Required Skill / Role', type: 'TEXT', displayOrder: 4, requiredForDraft: false, requiredForSubmit: true },
      { fieldKey: 'practiceCapability', label: 'Practice / Capability', type: 'TEXT', displayOrder: 5, requiredForDraft: false, requiredForSubmit: false },
      { fieldKey: 'headcount', label: 'Headcount', type: 'NUMBER', displayOrder: 6, requiredForDraft: false, requiredForSubmit: true },
      { fieldKey: 'allocationPercentage', label: 'Allocation Percentage', type: 'NUMBER', displayOrder: 7, requiredForDraft: false, requiredForSubmit: false },
      { fieldKey: 'locationPreference', label: 'Location Preference', type: 'TEXT', displayOrder: 8, requiredForDraft: false, requiredForSubmit: false },
      { fieldKey: 'billableImpact', label: 'Billable / Non-Billable', type: 'RADIO', displayOrder: 9, requiredForDraft: false, requiredForSubmit: false, options: [{ label: 'Billable', value: 'BILLABLE' }, { label: 'Non-Billable', value: 'NON_BILLABLE' }] },
      { fieldKey: 'businessJustification', label: 'Justification / Business Driver', type: 'TEXTAREA', displayOrder: 10, requiredForDraft: false, requiredForSubmit: false },
    ],
    dependencyRules: [
      {
        ruleKey: 'requires-project-setup',
        dependencyType: 'PRIOR_REQUEST',
        blockingStage: 'SUBMIT',
        message: 'A completed Project Setup request must be linked before submission.',
        requiredRequestTypeCode: 'PROJECT_SETUP',
        requiredStatus: 'COMPLETED',
        requiredEntityBindingKey: 'projectSetupRequest',
        resolutionMode: 'AUTO_OR_PICK',
        autoResolveIfSingle: true,
        promptIfMultiple: true,
      },
    ],
    workflowPolicy: {
      requiresApproval: true,
      workflowTemplateCode: 'RESOURCE_ALLOCATION_DEFAULT',
      slaProfileCode: 'STANDARD_OPERATIONS',
      defaultPriority: 'MEDIUM',
      autoApproveWhenNoChainResolved: false,
    },
    overridePolicy: {
      editableSections: ['identity-labels', 'commonFields', 'entityBindings', 'workflowPolicy'],
      mode: 'STANDARD_EDITABLE',
    },
  }),
  blueprint({
    schemaVersion: '1.0',
    identity: {
      code: 'PMO_OPERATIONAL_EXCEPTION',
      name: 'PMO Operational Exception',
      description: 'Capture and route PMO operational exceptions that need governed disposition, including rollback requests and signed-document mismatches.',
      domain: 'PROFESSIONAL_SERVICES',
      category: 'PMO Governance',
      icon: 'alert-triangle',
      version: 1,
      isSystemBlueprint: true,
      packCode: professionalServicesCorePack.code,
      maturityLevel: 'STANDARD',
    },
    runtime: {
      renderMode: 'DRAWER',
      complexityLevel: 'STANDARD',
      allowDraft: true,
      allowSubmit: true,
      allowEditAfterReturn: true,
      allowAttachments: true,
      maxAttachments: 10,
      maxAttachmentSizeMb: 10,
    },
    commonFields: [titleField, descriptionField, priorityField, urgencyField, neededByField, attachmentsField],
    entityBindings: [],
    customFields: [
      {
        fieldKey: 'exceptionType',
        label: 'Exception Type',
        type: 'SELECT',
        displayOrder: 1,
        requiredForDraft: false,
        requiredForSubmit: true,
        options: [
          { label: 'Signed document mismatch', value: 'SIGNED_DOCUMENT_MISMATCH' },
          { label: 'Commercial data conflict', value: 'COMMERCIAL_DATA_CONFLICT' },
          { label: 'Delivery readiness blocker', value: 'DELIVERY_READINESS_BLOCKER' },
          { label: 'Customer data gap', value: 'CUSTOMER_DATA_GAP' },
          { label: 'Rollback request', value: 'ROLLBACK_REQUEST' },
          { label: 'Other', value: 'OTHER' },
        ],
      },
      {
        fieldKey: 'impactedArea',
        label: 'Impacted Area',
        type: 'SELECT',
        displayOrder: 2,
        requiredForDraft: false,
        requiredForSubmit: true,
        options: [
          { label: 'Customer', value: 'CUSTOMER' },
          { label: 'Contract', value: 'CONTRACT' },
          { label: 'Project', value: 'PROJECT' },
          { label: 'Document', value: 'DOCUMENT' },
          { label: 'Resource', value: 'RESOURCE' },
          { label: 'Billing', value: 'BILLING' },
          { label: 'Other', value: 'OTHER' },
        ],
      },
      {
        fieldKey: 'impactedRecordReference',
        label: 'Impacted Record Reference',
        type: 'TEXT',
        displayOrder: 3,
        requiredForDraft: false,
        requiredForSubmit: false,
        helpText: 'Provide the customer, contract, project, request, or document reference that this exception relates to.',
      },
      {
        fieldKey: 'customerImpact',
        label: 'Customer Impact',
        type: 'SELECT',
        displayOrder: 4,
        requiredForDraft: false,
        requiredForSubmit: true,
        options: [
          { label: 'Blocked', value: 'BLOCKED' },
          { label: 'At risk', value: 'AT_RISK' },
          { label: 'Internal only', value: 'INTERNAL_ONLY' },
        ],
      },
      {
        fieldKey: 'requestedDisposition',
        label: 'Requested Disposition',
        type: 'SELECT',
        displayOrder: 5,
        requiredForDraft: false,
        requiredForSubmit: true,
        options: [
          { label: 'Correct source data', value: 'CORRECT_SOURCE_DATA' },
          { label: 'Proceed with exception approval', value: 'PROCEED_WITH_EXCEPTION_APPROVAL' },
          { label: 'Initiate rollback', value: 'INITIATE_ROLLBACK' },
          { label: 'Escalate to leadership', value: 'ESCALATE_TO_LEADERSHIP' },
        ],
      },
      {
        fieldKey: 'accountableOwner',
        label: 'Accountable Owner',
        type: 'USER_PICKER',
        displayOrder: 6,
        requiredForDraft: false,
        requiredForSubmit: true,
      },
      {
        fieldKey: 'impactSummary',
        label: 'Impact Summary',
        type: 'TEXTAREA',
        displayOrder: 7,
        requiredForDraft: false,
        requiredForSubmit: true,
      },
    ],
    dependencyRules: [],
    workflowPolicy: {
      requiresApproval: true,
      workflowTemplateCode: 'PMO_EXCEPTION_DEFAULT',
      slaProfileCode: 'STANDARD_OPERATIONS',
      defaultPriority: 'HIGH',
      autoApproveWhenNoChainResolved: false,
    },
    overridePolicy: {
      editableSections: ['identity-labels', 'commonFields', 'workflowPolicy'],
      mode: 'STANDARD_EDITABLE',
    },
  }),
];
